<a href="https://colab.research.google.com/github/gungungoyal314/PythonLearn/blob/main/Day8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
# 3d
import numpy as np
arr = np.array([[[1,2],
                [3,4]],
               [[5,6],
                [7,8]]
                ])
#print(arr.ndim) # 3d
#print(" = >>",arr[0]) # block

#print(" = >>" ,arr[0,0,0])# block  ---> row

#print(" =>>>" , arr[0,0,0])  # block --> row --> cols


print(arr[:,0])  # all block -> row -> 0
print(arr[:,:,0]) # all block -> all row  -> cols 0




[[1 2]
 [5 6]]
[[1 3]
 [5 7]]


In [16]:
# for loop on numpy
import numpy as np
arr1 = np.array([10,20,30,40])

print(arr1)
for i in arr1:
  print(i)


  # 2d
  arr1 = ([[1,2],[3,4],[5,6]])
  for i in arr1:
    for j in i:
      print(j)



  # 3d
  #3d
import numpy as np
arr= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
for i in arr:
  for j in i:
    for k in j:
      print(k)

[10 20 30 40]
10
1
2
3
4
5
6
20
1
2
3
4
5
6
30
1
2
3
4
5
6
40
1
2
3
4
5
6
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1
2
3
4
5
6
7
8


In [21]:
import numpy as np
arr = np.array([10,35,40,7,15,20])
print(arr)
print(np.sort(arr))   # ascending
print(np.sort(arr)[::-1]) # descending




[10 35 40  7 15 20]
[ 7 10 15 20 35 40]
[40 35 20 15 10  7]


In [28]:
import numpy as np

arr1 = arr.reshape(2,3)

print(arr1)
print(np.sort(arr1))   # ascending
print(np.sort(arr1)[::-1]) # descending

[[10 35 40]
 [ 7 15 20]]
[[10 35 40]
 [ 7 15 20]]
[[ 7 15 20]
 [10 35 40]]


In [35]:
# filter
import numpy as np
arr = np.array([10,20,30,40])
print(arr[arr> 30])
print(arr[0])
print(arr[0:3])
print(arr[0]+arr[1])


[40]
10
[10 20 30]
30


In [47]:
# where
import numpy as np
arr = np.array([10,20,30,40])
print(np.where(arr > 20 , " true" , "false"))





print(np.where(arr>20 ,2*arr ,arr))
# print


['false' 'false' ' true' ' true']
[10 20 60 80]
