<a href="https://colab.research.google.com/github/gungungoyal314/PythonLearn/blob/main/day_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# filter
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr > 20]
print(arr_f)


[ 90 200]


In [3]:
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr != 6]
print(arr_f)

[10 20 30  3  2]


In [4]:
import numpy as np
arr = np.array([10,20,30,15,3,2,18,8])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)


[15 18]


In [6]:
# fancy indexing
import numpy as np
arr = np.array([10,20,30,3,4,90,100])
print(arr)
arr_f = arr[[0,2]]
print(arr_f)


[ 10  20  30   3   4  90 100]
[10 30]


In [9]:
# where
import numpy as np
arr = np.array([10,20,30,3,4,90,100])
print(arr)
arr_w = np.where(arr > 9 , "True" , "False")
print(arr_w)


[ 10  20  30   3   4  90 100]
['True' 'True' 'True' 'False' 'False' 'True' 'True']


In [11]:
import numpy as np
arr = np.array([10,20,30,3,4,90,100])

arr_w = np.where((arr>10) & (arr<20) , arr*2 , arr+2)
print(arr_w)


[ 12  22  32   5   6  92 102]


In [12]:
# adding data and removing data
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])
arr1_arr2 = np.concatenate((arr1,arr2))
print(arr1_arr2)


[10 20 30  1  2  3]


In [13]:
# concatenate using 2d array
import numpy as np
arr1 = ([[1,2],[3,4]])
arr2 = ([[5,6],[7,8]])
arr1_arr2 = np.concatenate((arr1,arr2),axis=1)
print(arr1_arr2)



[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# vstack

import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([4,5,6])

arr_v = np.vstack((arr1,arr2))
print(arr_v)

[[10 20 30]
 [ 4  5  6]]


In [16]:
# hstack --> horizontally join column wise
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([4,5,6])

arr_v = np.hstack((arr1,arr2))
print(arr_v)

[10 20 30  4  5  6]
