<a href="https://colab.research.google.com/github/gungungoyal314/PythonLearn/blob/main/day_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# filter
import numpy as np
arr = np.array([10,20,3,4,90,200])
arr_f = arr[arr > 20]
print(arr_f)


[ 90 200]


In [3]:
import numpy as np
arr = np.array([10,20,30,6,3,2])
arr_f = arr[arr != 6]
print(arr_f)

[10 20 30  3  2]


In [4]:
import numpy as np
arr = np.array([10,20,30,15,3,2,18,8])
arr_f = arr[(arr>10) & (arr<20)]
print(arr_f)


[15 18]


In [6]:
# fancy indexing
import numpy as np
arr = np.array([10,20,30,3,4,90,100])
print(arr)
arr_f = arr[[0,2]]
print(arr_f)


[ 10  20  30   3   4  90 100]
[10 30]


In [9]:
# where
import numpy as np
arr = np.array([10,20,30,3,4,90,100])
print(arr)
arr_w = np.where(arr > 9 , "True" , "False")
print(arr_w)


[ 10  20  30   3   4  90 100]
['True' 'True' 'True' 'False' 'False' 'True' 'True']


In [11]:
import numpy as np
arr = np.array([10,20,30,3,4,90,100])

arr_w = np.where((arr>10) & (arr<20) , arr*2 , arr+2)
print(arr_w)


[ 12  22  32   5   6  92 102]


In [12]:
# adding data and removing data
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([1,2,3])
arr1_arr2 = np.concatenate((arr1,arr2))
print(arr1_arr2)


[10 20 30  1  2  3]


In [13]:
# concatenate using 2d array
import numpy as np
arr1 = ([[1,2],[3,4]])
arr2 = ([[5,6],[7,8]])
arr1_arr2 = np.concatenate((arr1,arr2),axis=1)
print(arr1_arr2)



[[1 2 5 6]
 [3 4 7 8]]


In [15]:
# vstack

import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([4,5,6])

arr_v = np.vstack((arr1,arr2))
print(arr_v)

[[10 20 30]
 [ 4  5  6]]


In [16]:
# hstack --> horizontally join column wise
import numpy as np
arr1 = np.array([10,20,30])
arr2 = np.array([4,5,6])

arr_v = np.hstack((arr1,arr2))
print(arr_v)

[10 20 30  4  5  6]


In [23]:
import numpy as np
arr1 = ([[1,2],[3,4]])
arr2 = ([[5,6],[7,8]])
arr1_arr2 = np.vstack((arr1,arr2))
print(arr1_arr2)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [20]:
import numpy as np
arr1 = ([[1,2],[3,4]])
arr2 = ([[5,6],[7,8]])
arr1_arr2 = np.hstack((arr1,arr2))
print(arr1_arr2)


[[1 2 5 6]
 [3 4 7 8]]


In [26]:
import numpy as np
arr = np.array([2,4,6,8,10])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))
print(np.prod(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.abs(arr))
print(np.unique(arr))
print(np.percentile(arr, 50))
print(np.quantile(arr, 0.5))
print(np.ptp(arr))
print(np.any(arr))
print(np.all(arr))





30
2
10
6.0
6.0
2.8284271247461903
8.0
3840
[ 2  6 12 20 30]
[   2    8   48  384 3840]
0
4
[ 2  4  6  8 10]
[ 2  4  6  8 10]
6.0
6.0
8
True
True


In [27]:
#np.sum(a) #-> Sum of all elements
#np.mean(a) #-> Average = Sum of elements / Number of elements
#np.median(a) #-> Middle value after sorting
#np.min(a) #-> Smallest value in array
#np.max(a) #-> Largest value in array
#np.var(a)# mean,difference,square,average | (sum = ddof) -> divide by array length
#np.std(a) #-> Standard Deviation = √Variance -> Measures spread of data
#np.prod(a) #-> Multiplication of all elements
#np.cumsum(a)# -> Cumulative (running) sum
#np.cumprod(a)# -> Cumulative (running) product
#np.argmin(a) #-> Index position of minimum value
#np.argmax(a) #-> Index position of maximum value
#np.abs(a) #-> Converts negative values to positive -> Absolute value (distance from zero)
#np.unique(a)# -> Returns unique values only -> Removes duplicates
#np.percentile(a, 50) #-> Finds percentage-based value -> 50th percentile = Median
#np.quantile(a, 0.5) #3-> Similar to percentile -> 0.5 = 50%
#np.ptp(a) #-> Range = Max - Min
#np.any(a) #-> True if at least one value is True


In [30]:
# handling missing values
import numpy as np
arr = np.array([10,20,np.nan,40])
print(arr)
print(np.isnan(arr))

[10. 20. nan 40.]
[False False  True False]
