<a href="https://colab.research.google.com/github/gungungoyal314/PythonLearn/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# numpy
!pip install numpy
import numpy as np


In [ ]:
l = [20, 30, 40, 50]
l*2

[20, 30, 40, 50, 20, 30, 40, 50]

In [ ]:
# power of numpy
import numpy as np
arr = np.array(l)
arr*2

array([ 40,  60,  80, 100])

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
arr[0]
print(arr[-1])

5


In [ ]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr = np.array([4]* 20)
arr

array([4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4])

In [ ]:
# change value
l  = [10,20,30,40]
l[0] = 100
print(l)

# numpy
arr = np.array([10,20,30,40])
arr[0] = 100
arr[1] = 400
print(arr)


[100, 20, 30, 40]
[100 400  30  40]


In [ ]:
arr = np.arange(10 , 51 , 2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
arr = np.arange(10 , 51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# value add = 2
import numpy as np
l  = [10,20,30,40]
arr = np.array(l)
print(arr+2)

[12 22 32 42]


In [ ]:
arr  = np.arange(100 , 1000 , 100)
arr

array([100, 200, 300, 400, 500, 600, 700, 800, 900])

In [ ]:
for i  in range(100 , 200 , 10):
  print(i)

100
110
120
130
140
150
160
170
180
190


In [ ]:
import numpy as np
# [[Row 1], [Row 2]]
matrix = np.array([[1, 2,3],
                   [3, 4,5]])

# Full array ko print karte hain
print("Yeha hai humara 2D Array:")
print(matrix)

# Ek single value nikalne ke liye

print(matrix[1, 2])

Yeha hai humara 2D Array:
[[1 2 3]
 [3 4 5]]
5


In [ ]:
# simple 2d example
print("list start")
l = [[1,2,3],[4,5,6]]
print(l)
print(l[0],1)
print("numpy start")




# 2d numpy
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr)

list start
[[1, 2, 3], [4, 5, 6]]
[1, 2, 3] 1
numpy start
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
